version: "3"

services:
  db:
    image: postgres:10.19-alpine
    environment:
      - POSTGRES_DB=hashcode
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "7432:5432"
    
    command: ["postgres", "-c", "log_statement=all"]
