default: &default
  host: localhost
  adapter: postgresql
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: 'postgres'
  pool: 30
  timeout: 5000
  gssencmode: disable

development:
  <<: *default
  database: development_db
  port: 7432

test:
  <<: *default
  database: test_db
  port: 7432

production:
  <<: *default
  database: production_db
  port: 7432
